//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id_product { get; set; }
        public string name { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<int> id_producttype { get; set; }
        public string description { get; set; }
    
        public virtual ProductType ProductType { get; set; }
    }
}
